version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: node_fulltask_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: node_fulltask
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
